import turtle

def draw_s():
    t=turtle.Turtle()
    t.penup()
    t.setpos(-270,50)
    t.pendown()
    t.pensize(3)
    t.pencolor("black")
    t.forward(80)
    t.backward(100)
    t.right(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.right(100)
    t.forward(100)

def draw_9():
    t=turtle.Turtle()
    t.penup()
    t.setpos(-150,50)
    t.pendown()
    t.pensize(3)
    t.pencolor("black")
    t.forward(80)
    t.backward(100)
    t.right(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.backward(190)
    t.left(80)
    t.forward(50)

def draw_6():
    t=turtle.Turtle()
    t.penup()
    t.setpos(35,-40)
    t.pendown()
    t.pensize(3)
    t.pencolor("black")
    t.backward(80)
    t.forward(100)
    t.left(90)
    t.backward(100)
    t.right(90)
    t.backward(100)
    t.right(90)
    t.backward(100)
    t.backward(80)
    t.right(80)
    t.backward(50)

def draw_5():
    t=turtle.Turtle()
    t.penup()
    t.setpos(100,50)
    t.pendown()
    t.pensize(3)
    t.pencolor("black")
    t.forward(80)
    t.backward(100)
    t.right(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.right(80)
    t.forward(100)
    



def draw_f():
    t=turtle.Turtle()
    t.penup()
    t.setpos(210,50)
    t.pendown()
    t.pensize(3)
    t.pencolor("black")
    t.forward(100)
    t.backward(100)
    t.right(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.backward(100)
    t.right(90)
    t.forward(100)

draw_s()
draw_9()
draw_6()
draw_5()
draw_f()

turtle.done()